apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ include "app.fullname" . }}-el
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: {{ include "app.fullname" . }}-github-push
      template:
        ref: {{ include "app.fullname" . }}
