kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "app.fullname" . }}-el-route
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: {{ include "app.fullname" . }}-el
spec:
  to:
    kind: Service
    name: {{ include "app.fullname" . }}-el
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None
