apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: {{ include "app.fullname" . }}-run-{{ .Release.Revision }}
  labels:
    tekton.dev/pipeline: build-maven
    app.kubernetes.io/name: {{ include "app.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  pipelineRef:
    name: {{ include "app.fullname" . }}-build
  serviceAccountName: pipeline
  timeout: 1h0m0s
  params:
    - name: appversion
      value: {{ .Chart.AppVersion }}
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: {{ include "app.fullname" . }}-build-pvc
    - name: source-helm
      persistentVolumeClaim:
        claimName: {{ include "app.fullname" . }}-build-pvc-helm
    - configMap:
        name: {{ include "app.fullname" . }}-maven-settings
      name: maven-settings